-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ MODULAR CONFIGURATION
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- colors.lua is generated by matugen and lives at ~/.config/hypr/colors.lua.
-- Same fresh-install gotcha as with the old colors.conf: it won't exist until a
-- wallpaper is picked through the Quickshell picker, so this require (and the
-- one in config/settings.lua) will error until then. Not automated yet, same
-- as before — just flagging it survived the migration unchanged.
require("colors")

hl.define_submap("passthru", function()
    -- Dummy bind to force Hyprland to register the submap in memory.
    -- Since we will never press this, all normal keystrokes fall through to Quickshell.
    hl.bind("SUPER + SHIFT + CTRL + ALT + F35", hl.dsp.exec_cmd("true"))
end)

-- --------------

require("config.monitors")
require("config.env")
require("config.autostart")
require("config.settings")
require("config.rules")
require("config.keybindings")
